echo '****************************************'
echo '*              SHORTCUTS               *'
echo '*  Super/Win + Enter: New Terminal     *'
echo '*        Super/Win + d: dmenu          *'
echo '*    Super/Win + Shift + d: rofi       *'
echo '* Super/Win + Shift + q: kill window   *'
echo '*                                      *'
echo '*               SCRIPTS                *'
echo '*        InitConfig.sh to make         *'
echo '*        initial configurations        *'
echo '****************************************'
